title: Jess Spayd | Data Scientist # your name (or website title) here
logo: "images/jess-roundframe.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)



 
theme: jekyll-theme-slate
